In [1]:
import pandas as pd
from certa.explain import CertaExplainer
from certa.utils import merge_sources
from certa.models.utils import from_type

In [2]:
dataset = 'abt_buy'
model_type = 'dm'
model = from_type(model_type)
model.load('/path/to/dm_model.pth')

In [3]:
def predict_fn(x):
    return model.predict(x)

In [4]:
datadir = '/path/to/dataset_dir'
lsource = pd.read_csv(datadir + '/tableA.csv')
rsource = pd.read_csv(datadir + '/tableB.csv')
gt = pd.read_csv(datadir + '/train.csv')
valid = pd.read_csv(datadir + '/valid.csv')
test = pd.read_csv(datadir + '/test.csv')

In [5]:
test_df = merge_sources(test, 'ltable_', 'rtable_', lsource, rsource, ['label'], [])

In [41]:
idx = 27
rand_row = test_df.iloc[idx]
l_id = int(rand_row['ltable_id'])
l_tuple = lsource.iloc[l_id]
r_id = int(rand_row['rtable_id'])
r_tuple = rsource.iloc[r_id]
rand_row.head()

label                                                                 0
ltable_description    samsung 46 ' series 5 lcd black flat panel hdt...
ltable_id                                                           572
ltable_name           samsung 46 ' series 5 lcd black flat panel hdt...
ltable_price                                                        NaN
Name: 27, dtype: object

In [42]:
l_tuple

id                                                           572
name           samsung 46 ' series 5 lcd black flat panel hdt...
description    samsung 46 ' series 5 lcd black flat panel hdt...
price                                                        NaN
Name: 572, dtype: object

In [43]:
r_tuple

id                                                           695
name                       samsung 4 series ln22a450 22 ' lcd tv
description    samsung ln22a450 22 ' widescreen 720p lcd hdtv...
price                                                     397.77
Name: 695, dtype: object

In [45]:
certa_explainer = CertaExplainer(lsource, rsource)
saliency_df, cf_summary, counterfactual_examples, triangles, lattices = certa_explainer.explain(l_tuple, r_tuple, predict_fn)

In [46]:
saliency_df.to_dict()

{'ltable_name': {0: 0.0625},
 'ltable_description': {0: 0.0325},
 'ltable_price': {0: 0.0325},
 'rtable_name': {0: 0.0225},
 'rtable_description': {0: 0.0125},
 'rtable_price': {0: 0.0125}}

In [48]:
counterfactual_examples

,ltable_name,ltable_description,ltable_price,rtable_name,rtable_description,rtable_price,alteredAttributes,droppedValues,copiedValues,nomatch_score,match_score,attr_count
0,lcd tv,samsung 46 ' series 5 lcd black flat panel hdt...,NaN,samsung 4 series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(ltable_name,)",[samsung 46 ' series 5 lcd black flat panel hd...,[lcd tv],0.065987,0.934013,2
22,samsung 4 series ln22a450 22,samsung 46 ' series 5 lcd black flat panel hdt...,397.77,samsung 4 series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(ltable_name, ltable_price)",[samsung 46 ' series 5 lcd black flat panel hd...,"[samsung 4 series ln22a450 22, 397.77]",0.116304,0.883696,2
21,samsung 4 series ln22a450 22,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,NaN,samsung 4 series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(ltable_name, ltable_description)",[samsung 46 ' series 5 lcd black flat panel hd...,"[samsung 4 series ln22a450 22, samsung ln22a45...",0.111736,0.888264,2
20,samsung 4 series ln22a450 22,samsung 46 ' series 5 lcd black flat panel hdt...,NaN,samsung 4 series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(ltable_name,)",[samsung 46 ' series 5 lcd black flat panel hd...,[samsung 4 series ln22a450 22],0.124058,0.875942,2
26,samsung 46 ' series 5 lcd black flat panel hdt...,samsung 46 ' series 5 lcd black flat panel hdt...,NaN,samsung ln46a550 46 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,1143.99,"(rtable_name, rtable_price)","[samsung 4 series ln22a450 22 ' lcd tv, 397.77]","[samsung ln46a550 46 ' lcd tv, 1143.99]",0.061806,0.938194,2
18,samsung 22 ' black flat panel lcd hdtv ln22a450,samsung 46 ' series 5 lcd black flat panel hdt...,NaN,samsung 4 series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(ltable_name, ltable_price)",[samsung 46 ' series 5 lcd black flat panel hd...,[samsung 22 ' black flat panel lcd hdtv ln22a4...,0.262956,0.737044,2
17,samsung 22 ' black flat panel lcd hdtv ln22a450,samsung 22 ' black flat panel series 4 lcd hdt...,NaN,samsung 4 series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(ltable_name, ltable_description)",[samsung 46 ' series 5 lcd black flat panel hd...,[samsung 22 ' black flat panel lcd hdtv ln22a4...,0.272071,0.727929,2
16,samsung 22 ' black flat panel lcd hdtv ln22a450,samsung 46 ' series 5 lcd black flat panel hdt...,NaN,samsung 4 series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(ltable_name,)",[samsung 46 ' series 5 lcd black flat panel hd...,[samsung 22 ' black flat panel lcd hdtv ln22a450],0.262956,0.737044,2
30,samsung 46 ' series 5 lcd black flat panel hdt...,samsung 46 ' series 5 lcd black flat panel hdt...,NaN,samsung ln46a550 46 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,1143.99,"(rtable_name, rtable_price)","[samsung 4 series ln22a450 22 ' lcd tv, 397.77]","[samsung ln46a550 46 ' lcd tv, 1143.99]",0.061806,0.938194,2
14,ln22a450 22 ' lcd tv,samsung 46 ' series 5 lcd black flat panel hdt...,397.77,samsung 4 series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(ltable_name, ltable_price)",[samsung 46 ' series 5 lcd black flat panel hd...,"[ln22a450 22 ' lcd tv, 397.77]",0.060760,0.939240,2
13,ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,NaN,samsung 4 series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(ltable_name, ltable_description)",[samsung 46 ' series 5 lcd black flat panel hd...,"[ln22a450 22 ' lcd tv, samsung ln22a450 22 ' w...",0.059131,0.940869,2
25,samsung 46 ' series 5 lcd black flat panel hdt...,samsung 46 ' series 5 lcd black flat panel hdt...,NaN,samsung ln46a550 46 ' lcd tv,samsung ln46a550 46 ' widescreen 1080p lcd hdt...,397.77,"(rtable_name, rtable_description)","[samsung 4 series ln22a450 22 ' lcd tv, samsun...","[samsung ln46a550 46 ' lcd tv, samsung ln46a55...",0.059300,0.940700,2
12,ln22a450 22 ' lcd tv,samsung 46 ' series 5 lcd black flat panel hdt...,NaN,samsung 4 series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(ltable_name,)",[samsung 46 ' series 5 lcd black flat panel hd...,[ln22a450 22 ' lcd tv],0.061933,0.938067,2
10,series ln22a450 22 ' lcd tv,samsung 46 ' series 5 lcd black flat panel hdt...,397.77,samsung 4 series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(ltable_name, ltable_price)",[samsung 46 ' series 5 lcd black flat panel hd...,"[series ln22a450 22 ' lcd tv, 397.77]",0.059832,0.940168,2
9,series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,NaN,samsung 4 series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(ltable_name, ltable_description)",[samsung 46 ' series 5 lcd black flat panel hd...,"[series ln22a450 22 ' lcd tv, samsung ln22a450...",0.058230,0.941770,2
8,series ln22a450 22 ' lcd tv,samsung 46 ' series 5 lcd black flat panel hdt...,NaN,samsung 4 series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(ltable_name,)",[samsung 46 ' series 5 lcd black flat panel hd...,[series ln22a450 22 ' lcd tv],0.061397,0.938603,2
28,samsung 46 ' series 5 lcd black flat panel hdt...,samsung 46 ' series 5 lcd black flat panel hdt...,NaN,samsung ln46a550 46 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(rtable_name,)",[samsung 4 series ln22a450 22 ' lcd tv],[samsung ln46a550 46 ' lcd tv],0.059815,0.940185,2
6,' lcd tv,samsung 46 ' series 5 lcd black flat panel hdt...,397.77,samsung 4 series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(ltable_name, ltable_price)",[samsung 46 ' series 5 lcd black flat panel hd...,"[' lcd tv, 397.77]",0.064568,0.935432,2
5,' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,NaN,samsung 4 series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(ltable_name, ltable_description)",[samsung 46 ' series 5 lcd black flat panel hd...,"[' lcd tv, samsung ln22a450 22 ' widescreen 72...",0.062846,0.937154,2
4,' lcd tv,samsung 46 ' series 5 lcd black flat panel hdt...,NaN,samsung 4 series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(ltable_name,)",[samsung 46 ' series 5 lcd black flat panel hd...,[' lcd tv],0.065935,0.934065,2
29,samsung 46 ' series 5 lcd black flat panel hdt...,samsung 46 ' series 5 lcd black flat panel hdt...,NaN,samsung ln46a550 46 ' lcd tv,samsung ln46a550 46 ' widescreen 1080p lcd hdt...,397.77,"(rtable_name, rtable_description)","[samsung 4 series ln22a450 22 ' lcd tv, samsun...","[samsung ln46a550 46 ' lcd tv, samsung ln46a55...",0.059300,0.940700,2
2,lcd tv,samsung 46 ' series 5 lcd black flat panel hdt...,397.77,samsung 4 series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(ltable_name, ltable_price)",[samsung 46 ' series 5 lcd black flat panel hd...,"[lcd tv, 397.77]",0.064623,0.935377,2
1,lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,NaN,samsung 4 series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(ltable_name, ltable_description)",[samsung 46 ' series 5 lcd black flat panel hd...,"[lcd tv, samsung ln22a450 22 ' widescreen 720p...",0.062905,0.937095,2
24,samsung 46 ' series 5 lcd black flat panel hdt...,samsung 46 ' series 5 lcd black flat panel hdt...,NaN,samsung ln46a550 46 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(rtable_name,)",[samsung 4 series ln22a450 22 ' lcd tv],[samsung ln46a550 46 ' lcd tv],0.059755,0.940245,2
27,samsung 46 ' series 5 lcd black flat panel hdt...,samsung 46 ' series 5 lcd black flat panel hdt...,NaN,samsung ln46a550 46 ' lcd tv,samsung ln46a550 46 ' widescreen 1080p lcd hdt...,1143.99,"(rtable_name, rtable_description, rtable_price)","[samsung 4 series ln22a450 22 ' lcd tv, samsun...","[samsung ln46a550 46 ' lcd tv, samsung ln46a55...",0.061266,0.938734,3
15,ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,samsung 4 series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(ltable_name, ltable_description, ltable_price)",[samsung 46 ' series 5 lcd black flat panel hd...,"[ln22a450 22 ' lcd tv, samsung ln22a450 22 ' w...",0.057687,0.942313,3
19,samsung 22 ' black flat panel lcd hdtv ln22a450,samsung 22 ' black flat panel series 4 lcd hdt...,NaN,samsung 4 series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(ltable_name, ltable_description, ltable_price)",[samsung 46 ' series 5 lcd black flat panel hd...,[samsung 22 ' black flat panel lcd hdtv ln22a4...,0.272071,0.727929,3
11,series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,samsung 4 series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(ltable_name, ltable_description, ltable_price)",[samsung 46 ' series 5 lcd black flat panel hd...,"[series ln22a450 22 ' lcd tv, samsung ln22a450...",0.056802,0.943198,3
7,' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,samsung 4 series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(ltable_name, ltable_description, ltable_price)",[samsung 46 ' series 5 lcd black flat panel hd...,"[' lcd tv, samsung ln22a450 22 ' widescreen 72...",0.061348,0.938652,3
3,lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,samsung 4 series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(ltable_name, ltable_description, ltable_price)",[samsung 46 ' series 5 lcd black flat panel hd...,"[lcd tv, samsung ln22a450 22 ' widescreen 720p...",0.061404,0.938596,3
23,samsung 4 series ln22a450 22,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,samsung 4 series ln22a450 22 ' lcd tv,samsung ln22a450 22 ' widescreen 720p lcd hdtv...,397.77,"(ltable_name, ltable_description, ltable_price)",[samsung 46 ' series 5 lcd black flat panel hd...,"[samsung 4 series ln22a450 22, samsung ln22a45...",0.104824,0.895176,3
31,samsung 46 ' series 5 lcd black flat panel hdt...,samsung 46 ' series 5 lcd black flat panel hdt...,NaN,samsung ln46a550 46 ' lcd tv,samsung ln46a550 46 ' widescreen 1080p lcd hdt...,1143.99,"(rtable_name, rtable_description, rtable_price)","[samsung 4 series ln22a450 22 ' lcd tv, samsun...","[samsung ln46a550 46 ' lcd tv, samsung ln46a55...",0.061266,0.938734,3